### PR TITLE
Solution article for 2024 day 02

### PR DESCRIPTION
**Pull request by spamegg1**
[Here](https://scastie.scala-lang.org/ey2v1yv5QwCBF7h0nqm5CA) is a convenient Scastie of the solution.

### CODE REVIEW

**Comment by SethTisue** [comment]
thank you!!

**Comment by SethTisue** [comment]
hmm, should I not have merged this until tomorrow? 🤔   @bishabosha ?

**Comment by bishabosha** [comment]
For spoilers? I don't think we had any policy before like that

**Comment by bishabosha** [comment]
it would be cool if there was some react/docusaurus package for spoiler tags (combined with a date filter?)

**Comment by SethTisue** [comment]
an argument for merging promptly is that then the page is available for community folks to add their links to

I think that probably outweighs any spoiler concerns

**Comment by bishabosha** [comment]
the page is already there in the morning when the cron job bot creates it about few mins after the challenge goes live

**Comment by bishabosha** [comment]
anyway I did find this interesting package https://github.com/abdullahtariq1171/react-spoiler, which I guess could put the whole article sandwich between spoiler tags

**Comment by SethTisue** [comment]
> the page is already there in the morning when the cron job bot creates it about few mins after the challenge goes live

oh, okay. in that case, I will try to hold off merging these PRs until the following day. it also gives more time for review, anyway

**Pull request merged**
