### PR TITLE
Add day 22 article.

### PR DESCRIPTION
**Pull request by AvaPL**
Hi,

I see that this one is missing so I wanted to share my solution :)

Here is a runnable version on Scastie with example input: https://scastie.scala-lang.org/fwKC4C6JQ5Oh6sHUGQM5BQ

### CODE REVIEW

**Comment by bishabosha** [comment]
hey I will get to reviewing this still, just been busy

**Comment by bishabosha** [comment]
Finally with 3.4 release calming down I have a chance to review this week

**Review by bishabosha — APPROVED** [review]
Thanks for writing this! I changed some small parts for readability

**Comment by AvaPL** [comment]
It was a pleasure, thank you!

**Pull request merged**
