### PR TITLE
Day 12, 2023

### PR DESCRIPTION
**Pull request by mbovel**

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM

**Comment by mbovel** [comment]
I have a 10x speedup by using a better cache, I'll update this tomorrow. Feel free to already merge this part.

**Comment by mbovel** [comment]
Ready to be reviewed/merged.

**Review by bishabosha — APPROVED** [review]
This is very nice! thanks for going the extra mile, and great touch with the complexity analysis

**Pull request merged**
