### PR TITLE
Adds my solutions for day 8

### PR DESCRIPTION
**Pull request by Jannyboy11**
I went for super optimized solutions this day. I am not sure how I ended up with my commit for day7 and a merge commit, but there is only 1 file changed.

### CODE REVIEW

**Review by Sporarum — COMMENTED** [review]
Hello, it looks nice !
Could you make the commit history just one commit ?

**Comment by Jannyboy11** [comment]
Alright, doing my best. I'm no expert with Git, need to find out how to get my commit on top of upstream.

**Comment by Jannyboy11** [comment]
Alright, fixed it by resetting and recommitting.

**Review by bishabosha — APPROVED** [review]
thanks!

**Pull request merged**
