### PR TITLE
Add blog post for day 13

### PR DESCRIPTION
**Pull request by adpi2**

### CODE REVIEW

**Review by bishabosha — APPROVED** [review]
very nice

**Comment by SethTisue** [comment]
just a nitpick, but `leftPart.reverse.zip(rightPart).forall(_ == _)` can be shortened to just `leftPart.reverse == rightPart`, can it?

**Comment by SethTisue** [comment]
though that doesn't lead as naturally into the `l1.zip(l2).count(_ != _)` of part 2

**Comment by SethTisue** [comment]
anyway, very nice solution, substantially more elegant than mine

it didn't occur to me to `type Tile = '.' | '#'`, probably because I've been doing Scala 2 for too long :-P

**Comment by adpi2** [comment]
> just a nitpick, but leftPart.reverse.zip(rightPart).forall(_ == _) can be shortened to just leftPart.reverse == rightPart, can it?

It's not exactly the same because `leftPart` and `rightPart` can be of different size and we need to trim the bigger one.

**Comment by SethTisue** [comment]
Ah, I see! In my code I trim separately first.

**Pull request merged**
